server:
  port: 3000

#spring:
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boomberry
    username: boomberry
    password: 123456

#    url: jdbc:postgresql://dpg-d56futshg0os73alt390-a.singapore-postgres.render.com/boomberry?sslmode=require
#    username: boomberry
#    password: wBvnqrb2Af9Mo1HkrVSudhrK097MJ4M7

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh